### ISSUE TITLE
Uncaught TypeError: Cannot read property 'digest' of null

### ISSUE THREAD

**Issue by sanedchez** [learn-co/learn-ide-3-tree#3]
[Before submitting, please enter steps to reproduce:]

1. ...
2. ...

**Learn IDE Package**: 3.0.0
**Learn IDE Core**: 3.0.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.6
**Thrown From**: [learn-ide-3-tree](https://github.com/learn-co/learn-ide-3-tree) package 2.0.2

### Stack Trace

Uncaught TypeError: Cannot read property 'digest' of null

```
At /private/var/folders/wz/fc812l3x4v17x2319h1cql4r0000gr/T/AppTranslocation/409ADBC7-0FD8-446A-841F-D0ADBD697FB6/d/Learn IDE 3.app/Contents/Resources/app.asar/node_modules/learn-ide-3-tree/lib/nsync/atom-helper.js:212

TypeError: Cannot read property 'digest' of null
    at Object.saveEditor (/app.asar/node_modules/learn-ide-3-tree/lib/nsync/atom-helper.js:212:15)
    at /app.asar/node_modules/learn-ide-3-tree/lib/nsync/initializer.js:197:27
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/nsync-fs/node_modules/event-kit/lib/emitter.js:82:11)
    at Nsync.updated (/app.asar/node_modules/nsync-fs/lib/nsync-fs.js:78:25)
    at close_write (/app.asar/node_modules/nsync-fs/lib/onmessage-strategies/change.js:49:11)
    at change (/app.asar/node_modules/nsync-fs/lib/onmessage-strategies/change.js:67:10)
    at onmessage (/app.asar/node_modules/nsync-fs/lib/onmessage.js:47:12)
    at Object.callback (/app.asar/node_modules/nsync-fs/lib/connection.js:18:16)
    at /app.asar/node_modules/phoenix/priv/static/phoenix.js:615:21
    at Array.map (native)
    at Channel.trigger (/app.asar/node_modules/phoenix/priv/static/phoenix.js:614:10)
    at /app.asar/node_modules/phoenix/priv/static/phoenix.js:1038:26
    at Array.forEach (native)
    at /app.asar/node_modules/phoenix/priv/static/phoenix.js:1037:12
    at Socket.decode (/app.asar/node_modules/phoenix/priv/static/phoenix.js:667:12)
    at Socket.onConnMessage (/app.asar/node_modules/phoenix/priv/static/phoenix.js:1023:12)
    at WebSocket.conn.onmessage (/app.asar/node_modules/phoenix/priv/static/phoenix.js:826:23)
```

### Commands

```
     -2:38.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
     -2:10.1.0 tree-view:expand-item (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:09.9.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:08.1.0 core:backspace (input.hidden-input)
     -1:39 editor:newline (input.hidden-input)
     -1:30.9.0 core:backspace (input.hidden-input)
     -1:29.5.0 autocomplete-plus:confirm (input.hidden-input)
  4x -0:49.1.0 core:backspace (input.hidden-input)
     -0:23.9.0 core:move-left (input.hidden-input)
     -0:20.2.0 learn-ide:reset-connection (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
     -0:18.7.0 editor:newline (input.hidden-input)
     -0:18.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
     -0:16.5.0 tree-view:duplicate (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:15.2.0 learn-ide:focus (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
```

### Non-Core Packages

```

```

**Comment by arye-eidelman** [comment]
## same issue on windows
[Before submitting, please enter steps to reproduce:]

1. ...
2. ...

**Learn IDE Package**: 3.0.0
**Learn IDE Core**: 3.0.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [learn-ide-3-tree](https://github.com/learn-co/learn-ide-3-tree) package 2.0.2


### Stack Trace

Uncaught TypeError: Cannot read property 'digest' of null

```
At C:\Users\aryed\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\learn-ide-3-tree\lib\nsync\atom-helper.js:212

TypeError: Cannot read property 'digest' of null
    at Object.saveEditor (/app.asar/node_modules/learn-ide-3-tree/lib/nsync/atom-helper.js:212:15)
    at /app.asar/node_modules/learn-ide-3-tree/lib/nsync/initializer.js:197:27
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/nsync-fs/node_modules/event-kit/lib/emitter.js:82:11)
    at Nsync.updated (/app.asar/node_modules/nsync-fs/lib/nsync-fs.js:78:25)
    at close_write (/app.asar/node_modules/nsync-fs/lib/onmessage-strategies/change.js:49:11)
    at change (/app.asar/node_modules/nsync-fs/lib/onmessage-strategies/change.js:67:10)
    at onmessage (/app.asar/node_modules/nsync-fs/lib/onmessage.js:47:12)
    at Object.callback (/app.asar/node_modules/nsync-fs/lib/connection.js:18:16)
    at /app.asar/node_modules/phoenix/priv/static/phoenix.js:615:21
    at Array.map (native)
    at Channel.trigger (/app.asar/node_modules/phoenix/priv/static/phoenix.js:614:10)
    at /app.asar/node_modules/phoenix/priv/static/phoenix.js:1038:26
    at Array.forEach (native)
    at /app.asar/node_modules/phoenix/priv/static/phoenix.js:1037:12
    at Socket.decode (/app.asar/node_modules/phoenix/priv/static/phoenix.js:667:12)
    at Socket.onConnMessage (/app.asar/node_modules/phoenix/priv/static/phoenix.js:1023:12)
    at WebSocket.conn.onmessage (/app.asar/node_modules/phoenix/priv/static/phoenix.js:826:23)
```

### Commands

```
     -4:51.1.0 learn-ide:reset-connection (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
     -4:48 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
```

### Non-Core Packages

```

```

**Comment by GaneshArvinth** [comment]
[Before submitting, please enter steps to reproduce:]

1. ...
2. ...

**Learn IDE Package**: 3.0.0
**Learn IDE Core**: 3.0.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [learn-ide-3-tree](https://github.com/learn-co/learn-ide-3-tree) package 2.0.2


### Stack Trace

Uncaught TypeError: Cannot read property 'digest' of null

```
At C:\Users\Tony\AppData\Local\learn_ide_3\app-3.0.0\resources\app.asar\node_modules\learn-ide-3-tree\lib\nsync\atom-helper.js:212

TypeError: Cannot read property 'digest' of null
    at Object.saveEditor (/app.asar/node_modules/learn-ide-3-tree/lib/nsync/atom-helper.js:212:15)
    at /app.asar/node_modules/learn-ide-3-tree/lib/nsync/initializer.js:197:27
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/nsync-fs/node_modules/event-kit/lib/emitter.js:82:11)
    at Nsync.updated (/app.asar/node_modules/nsync-fs/lib/nsync-fs.js:78:25)
    at close_write (/app.asar/node_modules/nsync-fs/lib/onmessage-strategies/change.js:49:11)
    at change (/app.asar/node_modules/nsync-fs/lib/onmessage-strategies/change.js:67:10)
    at onmessage (/app.asar/node_modules/nsync-fs/lib/onmessage.js:47:12)
    at Object.callback (/app.asar/node_modules/nsync-fs/lib/connection.js:18:16)
    at /app.asar/node_modules/phoenix/priv/static/phoenix.js:615:21
    at Array.map (native)
    at Channel.trigger (/app.asar/node_modules/phoenix/priv/static/phoenix.js:614:10)
    at /app.asar/node_modules/phoenix/priv/static/phoenix.js:1038:26
    at Array.forEach (native)
    at /app.asar/node_modules/phoenix/priv/static/phoenix.js:1037:12
    at Socket.decode (/app.asar/node_modules/phoenix/priv/static/phoenix.js:667:12)
    at Socket.onConnMessage (/app.asar/node_modules/phoenix/priv/static/phoenix.js:1023:12)
    at WebSocket.conn.onmessage (/app.asar/node_modules/phoenix/priv/static/phoenix.js:826:23)
```

### Commands

```
     -4:40.3.0 snippets:expand (input.hidden-input)
     -4:40.3.0 editor:indent (input.hidden-input)
  2x -4:39.3.0 core:backspace (input.hidden-input)
  2x -4:11.8.0 learn-ide:save (input.hidden-input)
     -3:28.3.0 snippets:next-tab-stop (input.hidden-input)
     -3:28.3.0 snippets:expand (input.hidden-input)
     -3:28.3.0 editor:indent (input.hidden-input)
  6x -3:26.1.0 core:backspace (input.hidden-input)
     -3:22.7.0 editor:newline (input.hidden-input)
     -1:34.2.0 snippets:next-tab-stop (input.hidden-input)
     -1:34.2.0 snippets:expand (input.hidden-input)
     -1:34.1.0 editor:indent (input.hidden-input)
     -1:29.4.0 learn-ide:save (input.hidden-input)
     -1:25.3.0 learn-ide:reset-connection (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
     -1:14.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
     -0:35.5.0 learn-ide:focus (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
```

### Non-Core Packages

```

```
